[project]
name = "job-crawler"
version = "0.1.0"
description = "Web crawler for job postings"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.27.0",
    "beautifulsoup4>=4.12.0",
    "lxml>=5.0.0",
    "playwright>=1.40.0",
]

[tool.uv]
dev-dependencies = []